blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.entrar, name='entrar'),
    path('logon/', views.inscrever, name='inscrever'),
    path('logon2/', views.inscrever2, name='inscrever2'),
    path('logon3/', views.inscrever3, name='inscrever3'),
    path('home/', views.home, name='home'),
    path('logout/', views.logout_view, name='logout'),
    path('novoPost/', views.novoPost, name='novoPost'),
    path('@<str:username>/', views.perfil, name='perfil')
]

djitter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
#    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(max_length=280)
    published_at = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)

    def timestamp(self):
        import datetime

        timestamp = datetime.datetime.now() - self.published_at

        if timestamp.days == 0:
            if timestamp.seconds <= 60:
                return 'Agora'

            elif timestamp.seconds <= 3600:
                return f'{int(timestamp.seconds/60)} m'

            else:
                return f'{int(timestamp.seconds/3600)} h'

        else:
            return f'{timestamp.days} d'

class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    bio = models.TextField(max_length=140, default='')

blog/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http.response import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'blog/main.html', context=None)

def entrar(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('blog:home'))

    if request.method == 'POST':
        from django.contrib.auth import authenticate, login

        username = request.POST['user']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)

            return HttpResponseRedirect(reverse('blog:home'))
        else:
            return HttpResponse('<h1>Não deu certo autenticar</h1>')


    return render(request, 'blog/entrar.html', context=None)

def inscrever(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('blog:home'))

    if request.method == "POST":
        from django.contrib.auth.models import User
        from django.db import IntegrityError
        from django.contrib.auth import authenticate, login

        username = request.POST['user']
        password = request.POST['password']

        try:
            newUser = User.objects.create_user(username=username, password=password)
            newUser.save()

        except IntegrityError:
            context = {
                'user_error': 'Este nome de usuário já está em uso :/'
            }

            return render(request, 'blog/inscrever.html', context)

        else:
            user = authenticate(username=username, password=password)
            login(request, user)

        return HttpResponseRedirect(reverse('blog:inscrever2'))

    return render(request, 'blog/inscrever.html', context=None)

def inscrever2(request):
    user = request.user

    context = {
        'user': user,
    }

    if request.method == 'POST':
        firstName = request.POST['firstName']
        lastName = request.POST['lastName']

        user.first_name = firstName
        user.last_name = lastName

        user.save()

        return HttpResponseRedirect(reverse('blog:inscrever3'))

    return render(request, 'blog/inscrever2.html', context)

def inscrever3(request):
    from .models import Profile

    user = request.user

    context = {
        'user': user
    }

    if request.method == 'POST':
        bio = request.POST['bio']

        profile = Profile(user=user, bio=bio)
        profile.save()

        return HttpResponseRedirect(reverse('blog:home'))

    return render(request, 'blog/inscrever3.html', context) 

@login_required(login_url='blog:entrar')
def home(request):
    from .models import Post

    loggedUser = request.user

    posts = Post.objects.order_by('-published_at')

    context = {
        'loggedUser': loggedUser,
        'posts': posts,
    }

    return render(request, 'blog/home.html', context)

def logout_view(request):
    from django.contrib.auth import logout

    logout(request)

    return HttpResponseRedirect(reverse('blog:index'))

@login_required(login_url='blog:entrar')
def novoPost(request):
    from .models import Post

    user = request.user

    postContent = request.POST['content']

    post = Post(author=user, content=postContent)
    post.save()

    return HttpResponseRedirect(reverse('blog:home'))

def perfil(request, username):
    from django.contrib.auth.models import User
    from .models import Profile, Post

    loggedUser = request.user

    user = User.objects.get(username=username)

    profile = Profile.objects.get(user_id=user.id)

    posts = Post.objects.filter(author_id=user.id).order_by('-published_at')

    context = {
        'user': user,
        'profile': profile,
        'posts': posts,
        'loggedUser': loggedUser,
    }

    if loggedUser == user:
        context['profileOwner'] = True

    return render(request, 'blog/perfil.html', context)

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href={% static 'blog/images/logo.png' %} type="image/x-icon">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=RocknRoll+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href={% static 'blog/styles/base.css' %}>
    <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>
    {% block extrahead %}{% endblock extrahead %}
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    <div id='Base'>
        <aside>
            <nav>
                <ul>
                    <li>
                        <a class='link' href={% url 'blog:home' %}>
                            <img src={% static 'blog/images/logo.png' %} alt="Djitter" /><span>Djitter</span>
                        </a>
                    </li>
                    <li>
                        <a class='link' href={% url 'blog:home' %}>
                            <i class="fas fa-home"></i><span>Home</span>
                        </a>
                    </li>
                    <li>
                        <a class='link' href={% url 'blog:perfil' loggedUser.username %}>
                            <i class="fas fa-user"></i><span>Perfil</span>
                        </a>
                    </li>
                    {% block extranav %}
                    {% endblock extranav %}
                    <li>
                        <a class='link' href={% url 'blog:logout' %}>
                            <i class="fas fa-door-open"></i><span>Sair</span>
                        </a>
                    </li>
                </ul>
            </nav>
            <footer>
                <p><a href="https://github.com/Lucas-R4mos/djitter">Sobre o Djitter</a></p>
            </footer>
        </aside>
        <main>
            <header>
                <h1>{% block page_title %}{% endblock page_title %}</h1>
            </header>
            <div class='content'>
                {% block content %}{% endblock content %}
            </div>
        </main>
    </div>
</body>

</html>

blog/templates/blog/entrar.html
{% extends 'blog/landing.html' %}

{% load static %}

{% block extracss %} <link rel="stylesheet" href={% static 'blog/styles/login.css' %}> {% endblock extracss %}

{% block title %}Djitter / Entrar{% endblock title %}

{% block main %}
<h1 class='landingH1'>Entrar no Djitter</h1>
<form action={% url 'blog:entrar' %} class='loginForm' method="post">
    {% csrf_token %}
    <label htmlFor="user">Usuário:</label><br />
    <input type="text" name="user" id="user" placeholder='Usuário' /><br />
    <label htmlFor="password">Senha:</label><br />
    <input type="password" name="password" id="password" placeholder='Senha' /><br /><br />
    <button type="submit">Entrar</button>
</form>
{% endblock main %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% load static %}

{% block extrahead %}
<link rel="stylesheet" href={% static 'blog/styles/home.css' %}>
{% endblock extrahead %}

{% block title %}Djitter / Home{% endblock title %}

{% block page_title %}Bem vindo, {{ loggedUser.username }}{% endblock page_title %}

{% block content %}
<form id='CreatePostForm' method="POST" action={% url 'blog:novoPost' %}>
    {% csrf_token %}
    <label for="content">
        <textarea name="content" id="content" placeholder='O que está acontecendo?'
        maxLength='280' required rows='5' cols='40' ></textarea>
    </label>
    <button class='CreatePost' type="submit">Postar</button>
</form>

{% if posts %}
{% for post in posts %}
<article>
    <h4><a href={% url 'blog:perfil' post.author %}>@{{ post.author }}<span></a> - {{ post.timestamp }}</span></h4>
    <p>{{ post.content }}</p>
</article>
{% endfor %}
{% else %}
<article>
    <p>Faça o primeiro post! :)</p>
</article>
{% endif %}
{% endblock content %}

blog/templates/blog/inscrever.html
{% extends 'blog/landing.html' %}

{% load static %}

{% block extracss %}
<link rel="stylesheet" href={% static 'blog/styles/login.css' %}> {% endblock extracss %}

{% block title %}Djitter / Inscrever-se{% endblock title %}

{% block main %}
<h1 class='landingH1'>Inscrever-se no Djitter</h1>
<form action={% url 'blog:inscrever' %} class='registerForm' method="post">
    {% csrf_token %}
    {% if user_error %}<small class='error'>{{ user_error }}</small><br />{% endif %}
    <label htmlFor="user">Usuário:</label><br />
    <input type="text" name="user" id="user" placeholder='Usuário' required /><br />
    <label htmlFor="password">Senha:</label><br />
    <input type="password" name="password" id="password" placeholder='Senha' required /><br /><br />
    <button type="submit">Avançar</button>
</form>
{% endblock main %}

blog/templates/blog/inscrever2.html
{% extends 'blog/landing.html' %}

{% load static %}

{% block extracss %}
<link rel="stylesheet" href={% static 'blog/styles/login.css' %}> {% endblock extracss %}

{% block title %}Djitter / Inscrever-se{% endblock title %}

{% block main %}
<h2 class='landingH1'>Diga-nos o seu nome, {{ user.username }} :)</h2>
<form action={% url 'blog:inscrever2' %} class='registerForm2' method="post">
    {% csrf_token %}
    <label htmlFor="firstName">Nome:</label><br />
    <input type="text" name="firstName" id="firstName" placeholder='Nome' required /><br />
    <label htmlFor="lastName">Sobrenome:</label><br />
    <input type="text" name="lastName" id="lastName" placeholder='Sobrenome' required /><br /><br />
    <button type="submit">Avançar</button>
</form>
{% endblock main %}

blog/templates/blog/inscrever3.html
{% extends 'blog/landing.html' %}

{% load static %}

{% block extracss %}
<link rel="stylesheet" href={% static 'blog/styles/login.css' %}> {% endblock extracss %}

{% block title %}Djitter / Inscrever-se{% endblock title %}

{% block main %}
<h2 class='landingH1'>Falta só mais uma coisa, {{ user.first_name }}!</h2>
<form action={% url 'blog:inscrever3' %} class='registerForm3' method="post">
    {% csrf_token %}
    <label htmlFor="bio">Conte-nos sobre você:<br />
        <textarea name="bio" id="bio" placeholder='Bio' maxLength='140' required rows='4'></textarea>
    </label><br /><br />
    <button type="submit">Concluir</button>
</form>
{% endblock main %}

blog/templates/blog/landing.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href={% static 'blog/images/logo.png' %} type="image/x-icon">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=RocknRoll+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href={% static 'blog/styles/landing.css' %}>
    {% block extracss %}{% endblock extracss %}
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <div id='landing'>
        <div class='landingLogo'>
            <img src={% static 'blog/images/logo.png' %} alt="Djitter"/>
        </div>
        <main>
            {% block main %}{% endblock main %}
        </main>
    </div>
    <footer class='landingFooter'>
        <p class='landingP'>
            Djitter BETA - Rede social experimental criada 
            por <a href="https://github.com/Lucas-R4mos">Lucas Ramos</a> usando Django
        </p>
    </footer>
</body>
</html>

blog/templates/blog/main.html
{% extends 'blog/landing.html' %}

{% load static %}

{% block extracss %}<link rel="stylesheet" href={% static 'blog/styles/main.css' %}>{% endblock extracss %}

{% block title %}Djitter{% endblock title %}

{% block main %}
<h1 class='landingH1'>Bem vindo ao Djitter</h1>
<p class='landingP'>Compartilhe experiências com amigos.</p>
<a href={% url 'blog:entrar' %}><button class='b-login'>Entrar</button></a>
<a href={% url 'blog:inscrever' %}><button class='b-register'>Registrar-se</button></a>
{% endblock main%}

blog/templates/blog/perfil.html
{% extends 'blog/base.html' %}

{% load static %}

{% block extrahead %}
<link rel="stylesheet" href={% static 'blog/styles/home.css' %}>
{% endblock extrahead %}

{% block title %}Djitter / {{ user.username }}{% endblock title %}

{% block page_title %}{{ user.username }}{% endblock page_title %}

{% block extranav %}
    {% if profileOwner %}
        <li>
            <a class='link' href="">
                <i class="fas fa-user-edit"></i><span>Editar</span>
            </a>
        </li>
    {% endif %}
{% endblock extranav %}

{% block content %}
    <article>
        <p><em>{{ user.first_name }} {{ user.last_name }}</em></p>
        <p>"{{ profile.bio }}"</p>
    </article>
    {% if posts %}
        {% for post in posts %}
            <article>
                <h4><a href={% url 'blog:perfil' post.author %}>@{{ post.author }}<span>
                </a> - {{ post.timestamp }}</span></h4>
                <p>{{ post.content }}</p>
            </article>
        {% endfor %}
    {% endif %}
{% endblock content %}